name: Secret Scan

on:
  workflow_call:  # reusable workflow
    inputs:
      repo-token:
        required: true
        type: string
      branch:
        required: true
        type: string
      repo-name:
        required: true
        type: string

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo-name }}
          token: ${{ inputs.repo-token }}
          ref: ${{ inputs.branch }}

      - name: Run Secret Scan
        run: |
          chmod +x scripts/run_secret_scan.sh
          ./scripts/run_secret_scan.sh $GITHUB_WORKSPACE

      - name: Upload Secret Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: secret-scan-report
          path: leaks.json
