name: Secret Scan

on:
  push:
    branches: [ 'dev', 'main' ]
  pull_request:

jobs:
  secret_scan:
    uses: SteveVInay/central-sec-pipeline/.github/workflows/secret-scan.yml@main
    with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.ref_name || github.head_ref || github.ref }}
      repo-name: ${{ github.repository }}
